from typing import Protocol

from app.dominio.modelos import Abogado, Registro


class RepositorioCostos(Protocol):
    def periodo(self) -> str: ...

    def abogados(self) -> list[Abogado]: ...

    def abogado(self, abogado_id: str) -> Abogado | None: ...

    def costo_de(self, abogado_id: str) -> float: ...

    def registros_de(self, abogado_id: str) -> list[Registro]: ...
