import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitBaseEntities1790980801808 implements MigrationInterface {
  name = 'InitBaseEntities1790980801808';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "abogados" (
        "id" character varying NOT NULL,
        "nombre" character varying NOT NULL,
        "nivel" character varying NULL,
        "area" character varying NULL,
        "activo" boolean NOT NULL DEFAULT true,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "PK_abogados" PRIMARY KEY ("id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "registros_trabajo" (
        "id" character varying NOT NULL,
        "abogadoId" character varying NOT NULL,
        "fechaTrabajo" date NOT NULL,
        "fechaCarga" date NOT NULL,
        "minutos" integer NOT NULL,
        "facturable" boolean NOT NULL,
        "cliente" character varying NOT NULL,
        "asunto" character varying NOT NULL,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "PK_registros_trabajo" PRIMARY KEY ("id"),
        CONSTRAINT "CK_registros_minutos_positivo" CHECK ("minutos" > 0),
        CONSTRAINT "FK_registros_trabajo_abogado"
          FOREIGN KEY ("abogadoId") REFERENCES "abogados"("id")
          ON DELETE RESTRICT ON UPDATE CASCADE
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "idx_registros_abogado_id" ON "registros_trabajo" ("abogadoId")`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_registros_fecha_trabajo" ON "registros_trabajo" ("fechaTrabajo")`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_registros_abogado_fecha" ON "registros_trabajo" ("abogadoId", "fechaTrabajo")`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_registros_facturable" ON "registros_trabajo" ("facturable")`,
    );

    await queryRunner.query(`
      CREATE TABLE "costos_mensuales_abogado" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY,
        "abogadoId" character varying NOT NULL,
        "periodo" character varying(7) NOT NULL,
        "sueldo" numeric(12,2) NOT NULL,
        "cargasSociales" numeric(12,2) NOT NULL,
        "gastosAsignados" numeric(12,2) NOT NULL,
        "costoTotal" numeric(12,2) NOT NULL,
        "horasFacturadasReportadas" numeric(10,2) NULL,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "PK_costos_mensuales_abogado" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_costos_abogado_periodo" UNIQUE ("abogadoId", "periodo"),
        CONSTRAINT "FK_costos_mensuales_abogado"
          FOREIGN KEY ("abogadoId") REFERENCES "abogados"("id")
          ON DELETE RESTRICT ON UPDATE CASCADE
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "idx_costos_abogado_id" ON "costos_mensuales_abogado" ("abogadoId")`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_costos_periodo" ON "costos_mensuales_abogado" ("periodo")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "costos_mensuales_abogado"`);
    await queryRunner.query(`DROP TABLE "registros_trabajo"`);
    await queryRunner.query(`DROP TABLE "abogados"`);
  }
}
